<a href="<?php echo $this->url('entries') ?>" class="btn btn-success">zurück</a>
<hr>
<?php if ($error) : ?>
    <div class="alert alert-danger"><?php echo $error ?></div>
<?php endif; ?>

<?php
    $form = $this->form;
    $form->setAttribute('action', join('/', [$this->url(), 'add']));
    $form->prepare();

    echo $this->form()->openTag($form);

    echo $this->formCollection($form);

    echo $this->form()->closeTag();
